version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - "@types/*"
      dev-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
      prefix-development: deps-dev
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
